pageinfo = [[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null]];
pagedata = [ ["./-elma365-store.html","BRIX Store solutions","BRIX Store is a catalog of ready-made solutions that expand the capabilities of the platform and system solutions. They include modules, work...",""],
["./404.html","404","404 Page not found",""],
["./ad-ldap-troubleshooting.html","AD/LDAP troubleshooting","This article describes the most common issues and errors that may occur when setting up and operating the AD/LDAP modules.",""],
["./ad_ldap.html","Active Directory/LDAP","The Active Directory/LDAP standard module allows you to import users from another corporate system to BRIX while retaining their login information...",""],
["./audit_extension.html","Security Audit report","During the audit process, records of all events registered in the system will be displayed in the report.",""],
["./audit_service.html","Security Audit","In BRIX you can log and analyze events related to changing the user permissions and data using Security Audit.",""],
["./compliance-management.html","Compliance Management","The Compliance Management business solution will help you manage customer documents and ensure that they comply with applicable laws and company p...",""],
["./electronic-signature.html","Digital signature providers (CryptoPro, NCA)","In BRIX, you can use CryptoPro and NCA standard modules for signing documents with a digital signature. They allow you to sign attributes of app i...",""],
["./employee-engagement.html","Employee Engagement","The Employee Engagement solution is designed to monitor employee engagement, evaluate and increase loyalty, and improve the company culture.",""],
["./external-users-ad-ldap.html","Import external users from AD/LDAP","Apart from internal users, you can import external users into BRIX. They will be able to interact only with the external portal.",""],
["./groups-ad-ldap.html","Import groups from AD/LDAP","You can automatically distribute the imported internal users between groups that they belonged to in the other system.",""],
["./import_ad_ldap.html","Import internal users from AD/LDAP ","When you set up an integration with AD/LDAP, you can import users from your server into BRIX.",""],
["./leave_management.html","Leave Management","The Leave Management solution is designed to automate leave requests and approvals, PTO calculation, and scheduling.",""],
["./marketing_approval.html","Marketing","The Marketing solution is intended for automating the entire process of working with marketing content, from creation to storage. It coordinates t...",""],
["./operations-ad-ldap.html","Work with import and synchronization","A list of recent import and synchronization operations by internal and external users and groups is available in the AD/LDAP module settings. You ...",""],
["./search.html","search","Platform ECM CRM Service Projects Business Solutions API SDK In this topic BRIX SDK API Platform ECM Service Projects Send feedback Ask a question...",""],
["./ses.html","Simple electronic signature","To sign app item properties, document files and approval decision with a simple electronic signature, the SES module is available in BRIX.",""],
["./sync-employee-data-ad-ldap.html","Record employee information from AD/LDAP","The Employees system app stores additional information about users: position, department, contact information, etc. You can configure synchronizat...",""],
["./telephony-sipnet.html","SIPNET IP telephony","The module for connecting to the SIPNET IP telephony provider allows you to identify a customer by number, open a page of a related app, such as a...",""],
["./telephony-zadarma.html","Zadarma IP telephony","The module allows you to connect the Zadarma IP telephony provider to the BRIX system. Enable it to make and receive calls in the BRIX interface, ...",""],
["./user-status-ad-ldap.html","Statuses of imported users","Besides standard user statuses, such as Active, Invited, and Locked, as well as Not registered (for external users), imported ...",""],
["./work-with-document-compliance.html","Working with the Document compliance app","The Document compliance app allows you to request documents from customers in case of compliance issues. The app includes the Document request&#38;nbs...",""],
["./work-with-employee-engagement-recognition.html","Working with recognition tools","Employee Recognition The Employee Recognition app helps employees express gratitude to each other and shows how valuable each person is to the com...",""],
["./work-with-employee-engagement-surveys.html","Working with surveys","Surveys help you measure how engaged and motivated your employees are. The Employee Engagement solution offers three survey tools: Employee Pulse ...",""],
["./work-with-onboarding-compliance.html","Working with the Onboarding compliance app","The Onboarding compliance app is designed to help you ensure that documents provided during client onboarding are compliant with company policies ...",""]];
