pageinfo = [[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null]];
pagedata = [ ["./360012584940.html","How the CRM workspace is organized","The CRM workspace helps you streamline the customer relationship. You can manage leads and deals, assign responsible employees, as well ...",""],
["./360012584960.html","Contacts","The CRM &#62; Contacts app stores detailed information about the contact persons of client companies.",""],
["./360012584980.html","Companies","The Companies app stores detailed information about the companies you work with. To go to the app, open CRM &#62; Companies.",""],
["./360012585020.html","Revenue forecast","The Revenue Forecast report provides information about the planned revenues for the selected pipeline. This allows you to forecast the a...",""],
["./360012596920.html","Deal page","A deal&#39;s page stores all important information about it: the client company name and contact person, current tasks, history of communications with...",""],
["./360012597020.html","Unallocated deals page","In the Deals app, the Unallocated pipeline is added by default, which displays a list of all deals with the New status. When the status is changed...",""],
["./360012597080.html","Deal pipeline view","You can change the way deals are displayed in pipelines. The default view is Kanban board. It helps you track the progress of sales in real time. ...",""],
["./360012617440.html","Create or delete a deal","In BRIX, you can create deals manually, add them automatically using web forms and the provided API, or import them from .xlsx&#38;nbsp...",""],
["./360012617640.html","Move a deal to another pipeline","A company can have multiple pipelines, for example, for wholesale and retail sales or for different business lines. Deals can be moved from one pi...",""],
["./360012680859.html","Deal dynamics","The Deal Dynamics report shows how the statuses of deals assigned to a specific employee in a selected pipeline changed over a period of time.",""],
["./360012680899.html","Deals","With BRIX, it is easy to track your deals throughout different sales pipelines. All important data is always at hand: you can open a dea...",""],
["./360012693479.html","Search and filters in the CRM workspace","To quickly find a deal, lead, company, or other app item of the CRM workspace, use search. You can search by name, app parameters, or by...",""],
["./360012693559.html","Deal pipeline","A pipeline is a tool for tracking the flow of deals from the initial contact until they are closed. You can always be aware of the number of deals...",""],
["./360012693999.html","Manage status. Close a deal","When the status of a deal changes, the deal progresses from one stage of the pipeline to another. Statuses can be changed manually or automaticall...",""],
["./360012715039.html","Web forms","A web form is a form where a user can enter data (for example, a phone number and an email) and send it to you. You can use these forms to accept ...",""],
["./360012770319.html","Access settings for CRM apps","BRIX provides flexible access settings for CRM apps and their items and allows you to limit access to lead and deal pipelines.",""],
["./360012911980.html","CRM tasks","CRM tasks are a special type of tasks that help to organize the work of sales managers with leads, deals, or companies. Any task associated with s...",""],
["./360013063359.html","Telephony","In BRIX, you can configure integration with IP telephony providers to make and receive calls from customers, as well as store and analyze call data.",""],
["./404.html","404","404 Page not found",""],
["./actions-with-email.html","Email organizing options","As in other email clients, emails in BRIX are organized into Inbox, Sent, Trash, Drafts, and Starred folders.",""],
["./all-deals.html","All deals","The All pipeline displays the deals available to the user from all pipelines. The deal entries are shown as a table. This view cannot be changed.",""],
["./all_leads.html","All leads page","By default, the Leads app contains a page called All. It shows all leads available to the user from all existing pipelines.",""],
["./api-in-marketing.html","API methods in marketing","You can use API methods to retrieve segment data and subscriber lists from an external system. For example, a segment of subscriber emails can be ...",""],
["./assign-nurturing-stage.html","Assign nurturing stages","In BRIX, sales employees perform various activities to communicate with the client. When scheduling these activities, users indicate a specific co...",""],
["./call-card.html","Customize a call page","By default, a call page is configured in each connected telephony module.  ",""],
["./call-summary-card.html","Customize a summary information page for a call","If you have a license for the BRIX Communication Management system solution, a sales rep can open a summary page for an incoming or outgoing call....",""],
["./campaigns.html","Bulk email campaigns","The Bulk email campaigns app is used to create and store email campaigns sent at scheduled times to subscriber emails in the selected segment.",""],
["./change-lead-pipeline.html","Move a lead to another pipeline","Your company may have several pipelines. For instance, pipelines for leads obtained through free webinars, contextual advertising, and those who d...",""],
["./closing_ratio.html","Conversion of leads and deals","Leads or Deals Conversion is a report that shows how many items have been moved from one status to another. The chart shows the percentage di...",""],
["./companies-settings.html","Companies app settings","Only users included in the Administrators group can configure the settings of the Companies app.",""],
["./configure-activity-log.html","Activity log settings","The system stores records of the interaction between the sales department and the contact. Created and executed CRM activities are recorded, as we...",""],
["./configure-crm-task-page.html","Customize CRM task pages","When assigning a CRM task, the author enters information that the sales manager needs to complete the job. This information is displayed on the ta...",""],
["./connect-email.html","Connect an email to an account","You can connect each BRIX account with one email address. To link an email to your account, follow these steps:",""],
["./connect-telephony.html","Connect an IP telephony provider","To receive and make calls in BRIX, install and configure the integration module for an IP telephony provider.",""],
["./contact-page.html","Contact page","On the contact page, information about the representative of the client company is stored: their name, position, contact details, newsletter prefe...",""],
["./contacts-settings.html","Contacts app settings","Only users included in the Administrators group can change the Contacts app’s settings.",""],
["./corporate-email.html","Configure the list of available email services","When connecting personal email accounts in the Email workspace, users select an email service from a list. Available options are specified by...",""],
["./create-catalog-products.html","Create a product catalog","You can proceed to filling the product catalog if the directories of the Product Catalog workspace are populated. The created product will become ...",""],
["./create-custom-crm-task.html","Create custom CRM task type","CRM tasks are used to organize, plan, and control the work of sales department employees. They include any actions with leads, deals, companies, e...",""],
["./create-delete-contact.html","Create or delete a contact","In BRIX, you can create contacts manually, add them automatically using web forms and the provided API, or import them from .xlsx&#38;n...",""],
["./create-journey-map.html","Create a customer journey map","You can add a new customer journey map on the Customer journey maps page",""],
["./create_delete_lead.html","Create or delete a lead","BRIX allows you to create leads manually, add them automatically using web forms and the provided API, or import them from .xlsx&#38;nb...",""],
["./crm-events-processing.html","Event handling in CRM tasks","For CRM tasks, you can create event handlers to track various actions and trigger a configured script or business process. The event handler is co...",""],
["./crm-functions.html","CRM features","The BRIX CRM system solution is built on on the BRIX platform and extends its capabilities. It includes workspaces, apps, pages, widgets, bus...",""],
["./crm-mass-actions.html","Actions with leads and deals","Customize the activity buttons The system administrator can customize activity buttons for each pipeline in the Leads and Deals apps. For example,...",""],
["./crm-task-settings.html","CRM task settings","CRM tasks help to arrange the sales department’s work with customers. They allow you to track managers’ activities on leads, deals, companies, con...",""],
["./crm_objects.html","Directories in the CRM workspace","The Directories store the data used in the CRM workspace. For better usability, the data is presented as lists and tables. Dir...",""],
["./crm_overview.html","Set up BRIX CRM","BRIX CRM allows you to set up efficient sales processes, organize communications with customers, streamline and monitor employees&#39; work, plan...",""],
["./customer-journey-maps.html","Customer journey maps","A customer journey map is a visual tool using a CJM editor for setting up and executing trigger email campaigns. It allows the user to create a sc...",""],
["./duplicate-checking.html","Detect duplicates when creating new app items","If an app has active duplicate rules, the system makes a duplicate check when a new app item is being saved. The field values of the new item are ...",""],
["./duplicates-advanced-settings.html","Advanced duplicate search settings","For all duplicate search rules configured in a workspace, you can:",""],
["./duplicates-events-processing.html","Event processing in duplicates","When the search for similar items is enabled in the app, you can create an event handler that will track the merging of duplicates and trigger the...",""],
["./duplicates.html","Duplicates in the CRM workspace","Sometimes two or more app items created in BRIX, such as leads, deals, companies, or contacts, happen to be storing the same data. These item...",""],
["./duplicate_settings.html","Create and configure rules","You can adjust the duplicate detection rules preconfigured for apps from the CRM workspace, as well as set your own rules in any system workspace.",""],
["./email-link-settings.html","Configure linking emails with app items","Users can link emails from the Email workspace to app items so that they are displayed on app item pages. For example, a manager adds their dialog...",""],
["./email-workspace-structure.html","How the Email workspace is organized","When you connect an email to an BRIX account, fifty most recent emails from your mailbox will be uploaded to the Email workspace. After that, the ...",""],
["./email-workspace.html","Email","The Email workspace is an email client built into BRIX. Every user can connect their personal email to their account on the platform, and read and...",""],
["./gateways-in-journey-maps.html","Gateways in a customer journey map scenario","A gateway splits the execution of a customer journey map scenario into several paths for different subscriber groups, depending on the conditions ...",""],
["./journey-maps-designer.html","Customer journey map designer","In the customer journey map designer, you can create a map scenario as a chain of triggers, activities, gateways, and events, and also configure s...",""],
["./journey-maps-page.html","Customer journey map page","To view a map’s page, go to Customer journey maps and click on the map’s name.",""],
["./journey-maps-parameters.html","Start and end parameters of a customer journey map","If the map scenario is ready, in the top panel of the designer, click Publish. In the opened window, set the following options:",""],
["./journey-maps-scenario.html","Create a customer journey map scenario","A customer journey map scenario is a chain of sequentially executed triggers, events, and activities for sending emails to subscribers.",""],
["./journey-maps-use-cases.html","Use cases for customer journey map scenarios","Case 1. Invitation to a webinar Let’s configure sending a webinar invitation to the subscribers of the selected segment that are specified in the ...",""],
["./leads.html","Leads","In BRIX you can organize your sales department work at all stages: from the very first contact to a closed deal.",""],
["./leads_layout.html","Lead pipeline view","You can change the way leads are displayed in a pipeline. The default view is Kanban board. It allows you to easily monitor your prospects in real...",""],
["./leads_pipeline.html","Lead pipeline","A Lead pipeline is a tool that shows how many leads are currently at each qualification stage, who is responsible for them, and wha...",""],
["./lead_page.html","Lead page","A lead’s page stores all the important information about a lead: the company’s name and contact person, current tasks, status, etc.",""],
["./lead_status.html","Manage statuses. Lead qualification","When a lead’s status changes, it moves from one stage of the pipeline to another. Statuses can be assigned manually or within business processes. ...",""],
["./link-email.html","Link an app item with an email","To save all important information from customer emails and make it available to your coworkers, you can link emails with BRIX app items.",""],
["./mailing-lists.html","Segments of subscriber emails","In the Segments of subscriber emails app, you can set up segments based on customer preferences. This allows you to organize your base of subscrib...",""],
["./manual_duplicate_search.html","Detect duplicates among existing app items","App items with overlapping data can be found not only when a new item is being created, but also when searching for duplicates among existing app ...",""],
["./mark-as-duplicate.html","Mark an app item as a duplicate","If similar items are found in the system as a result of the duplicate search, one of them can be marked as a duplicate. In this case, a link to th...",""],
["./marketing-report.html","Engagement report","You can analyze the indicators of sent email campaigns using the Engagement report. The data for this report is imported from the connected email ...",""],
["./marketing-settings.html","Configure the Marketing workspace","In the Marketing workspace settings, you can change the parameters by which segments of subscriber emails are created, i.e., customers from the Co...",""],
["./marketing.html","Marketing","The Marketing workspace is a part of the BRIX CRM system solution and is used to send email newsletters and manage your customer base from the BRI...",""],
["./new_leads.html","Unallocated leads page","By default, the Leads app contains a page called Unallocated. All newly created leads with the New status are automatically added to this page. Wh...",""],
["./page-of-email.html","Email page","To read an email, open one of the folders in the app menu and click an email in the list. The email page will open. Here you can see the panel wil...",""],
["./preferences.html","Preference categories","The Preference categories app creates and stores subjects for email campaigns that are sent from the Marketing workspace to subscribers’ emails.",""],
["./product-catalog-settings.html","Fill in the directories of the Product Catalog workspace","The directories of the Product Catalog workspace are used to create company products and contain their attributes, categories, and groups used to ...",""],
["./product-catalog.html","Product Catalog","In the Product Catalog workspace, you can create a hierarchical catalog of company products with attributes that can be filled using customizable ...",""],
["./sales-executive-dashboard.html","Sales manager dashboard","The Sales Manager Dashboard page shows reports that help the CCO and sales managers to analyze how efficiently sales reps work with leads and deals.",""],
["./sales-manager-dashboard.html","Sales rep dashboard","Sales rep dashboard allows users responsible for sales to view information about leads and deals assigned to them. They also help track CRM tasks ...",""],
["./search.html","search","Platform ECM CRM Service Projects Business Solutions API SDK In this topic BRIX SDK API Platform ECM Service Projects Send feedback Ask a question...",""],
["./select-catalog-product.html","Select a product on the app item page","Let’s consider the example of working with products created in the Product Catalog workspace in the Leads app.",""],
["./send-email.html","Compose an email","There are three ways to send an email in the system.",""],
["./subscribers.html","Subscribers","The Subscribers page displays the list of customers who have agreed to receive email campaigns. Subscribers are all contacts from the CRM workspac...",""],
["./telephony.html","Telephony workspace","Call data that is received and processed in BRIX is stored in the Telephony workspace.",""],
["./template-editor.html","Template editor","You can create a custom email template using the editor tools. The email editor is available:",""],
["./templates.html","Email templates","The Email templates app stores templates for creating bulk and triggered email campaigns. Here you can:",""],
["./triggers-in-journey-maps.html","Triggers in a customer journey map scenario","A trigger is used in a customer journey map scenario to initiate a transition to the next step. A trigger is placed after the Segment block and tr...",""],
["./view-activity-log.html","Track activity log","Activities are actions of sales managers and clients’ responses aimed at maintaining communication and closing the deal. Information about activit...",""],
["./work-with-call.html","Work with a call","Once the system administrator has configured the integration with the telephony provider and the call page, the sales rep can:",""]];
