pageinfo = [[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null]];
pagedata = [ ["./404.html","404","404 Page not found",""],
["./block-list.html","Blocklist","You can restrict user accounts from sending messages to live chats via external channels such as instant messengers and email. Note that you canno...",""],
["./block-session.html","Lock a session","Operators with Online status and supervisors can mark active sessions as spam.",""],
["./chat-lines-processes.html","Configure automatic process start","Using business processes in live chats helps operators work faster, as certain actions are automated.",""],
["./chat-lines-routing.html","Configure message routing","You can assign groups of employees who will be working with requests in a live chat.",""],
["./chat-lines-templates.html","Response templates","Response Templates are directories located in the Live Chats workspace. Operators can fill them with entries that provide answers to fre...",""],
["./chatdesk_external_users.html","Write to live chats from messengers, by email, or in an online LiveChat","The Live Chats workspace helps streamline communication with your external users: partners and customers. ",""],
["./chatdesk_internal_users.html","Write to live chats in BRIX","A live chat can be set up for different types of users: external users such as customers and partners, or internal users, such as company employees.",""],
["./chat_lines.html","Live chats","The Live Chats workspace is a versatile chat support center that allows you to communicate with employees, partners, and customers.",""],
["./chat_reports.html","Reports","The Report tool helps you analyze the performance of your live chats. You can check the efficiency of operators for each live chat and a...",""],
["./connection_to_line.html","Connect messengers to a live chat","You can connect instant messengers to a live chat so that your customers can contact you any way they like. The operators will see all the message...",""],
["./create-session.html","Initiate a session with an external user","If there are messengers or an email account connected to a live chat, operators of this live chat can create new sessions and initiate conversatio...",""],
["./create_line.html","Create a live chat","To create a communication channel for your external and internal users, add and set up a live chat. Your colleagues or partners will be able to co...",""],
["./custom-messenger-settings.html","Set up interaction requests in an arbitrary messenger","General information The naming, method types, and JSON response structure are developed in accordance with the accepted BRIX standards and cannot ...",""],
["./custom-messenger.html","Arbitrary messengers","An arbitrary messenger is a custom communication application created specifically for your company and used by your employees. Such messengers can...",""],
["./delete_line.html","Delete a live chat","You can delete a live chat if you don&#39;t need it any longer.",""],
["./export-session-parameters.html","Export session parameters","The system administrator can download information about session names, live chats, channels, dates of last activity, clients, etc. as a .xlsx or ....",""],
["./general-live-chat-settings.html","General live chat settings","After creating one or more Live Chats, you can change the parameters that affect the work of employees in all Live Chats configured in the system....",""],
["./inbox.html","Connect an email account to a live chat","You can connect a live chat with an email account so that your email can become one of the channels you use to help your customers. Clients will w...",""],
["./live-chat-groups.html","Groups of operators and supervisors","In the Live Chats workspace, permissions and responsibilities are group-based. This means that user groups assigned to a live chat as operato...",""],
["./live-chats-structure.html","How the Live Chats workspace is organized","Here is the list of the main terms you may encounter while working with the Live Chats workspace:",""],
["./livechat-auto-login.html","Automatic authentication in LiveChat","Configure automatic user authentication in LiveChat. Then, after authentication on a website or portal, the user will not have to fill out another...",""],
["./livechat-on-portal.html","Add LiveChat to a portal","You can embed an online LiveChat on a website or portal using the Code widget. Let&#39;s consider an example of such placement on an external portal.",""],
["./livechat-utm.html","UTM tags in LiveChat","When creating a new session with a user who contacted via the LiveChat, the following UTM tags are automatically captured in BRIX: ",""],
["./livechat.html","Create an online LiveChat for your website","LiveChat is an online chat for communicating with customers. You can set up LiveChat in BRIX, connect it to a live chat, and then embed it on an e...",""],
["./operator-status.html","Operator status","With the BRIX Service solution, operators and supervisors can set the working status. It affects the processing of messages in the Live Chats work...",""],
["./search.html","search","Platform ECM CRM Service Projects Business Solutions API SDK In this topic BRIX SDK API Platform ECM Service Projects Send feedback Ask a question...",""],
["./service-functions.html","Service features","The BRIX Service solution is built on the BRIX platform and enhances its capabilities for communication with customers.",""],
["./service_overview.html","Set up the BRIX Service solution","BRIX Service is a system solution you can use to create a single platform for communicating with employees, customers, and partners.",""],
["./session-processes.html","Manually start a business process","While communicating with a client, the operator can start a business process directly on the session page.",""],
["./session-settings.html","Configure a session","You can configure sessions by changing the list of their parameters. Parameters are used to store information about a session. They are shown on i...",""],
["./sla-in-live-chats.html","Configure SLA in live chats","SLA standards reflect service level agreements with the customer. In the system, you can set standard deadlines for processing live chat messages,...",""],
["./telegram.html","Telegram","Connect a live chat to Telegram to let customers send text and voice messages, as well as files and images, using this instant messenger. Operator...",""],
["./telegrambot.html","TelegramBot","You can connect TelegramBot to a live chat so that customers and partners can send their requests via messenger and receive a response generated i...",""],
["./whatsapp.html","WhatsApp","You can connect WhatsApp to a live chat so that customers can send their requests in the instant messenger, while operators reply directly from th...",""],
["./working_in_chat.html","Process incoming messages","When someone sends a message to a live chat, all operators of this live chat are notified, and a counter of new requests appears in the bottom lef...",""]];
