pageinfo = [[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null]];
pagedata = [ ["./360009671252.html","Forms of Document type apps","The form of a Document app item contains detailed information about the document. You can configure different page configurations for different do...",""],
["./360009923631.html","Document type apps","Document type apps are used for creating documents in BRIX, such as agreements, memos, invoices and so on.",""],
["./360010245000.html","Ready-made document routes","In BRIX, you can send Files and documents added to app items for approval or information to your coworkers.",""],
["./360011730580.html","How to configure a document route","All steps of a document lifecycle make up the document’s route. Any route can be automated by means of a business process. In a process, you can d...",""],
["./360011852980.html","File vs. document-type app","When introducing document management workflows in BRIX, you can work both with files and document type apps. There are some conceptual differences...",""],
["./360011855460.html","Monitor documents by status","In a company, any document moves through a certain number of stages, which are called the lifecycle. First, a document is created and sent for app...",""],
["./360011901900.html","Access to documents and files","Every organization has a hierarchy of authority that describes what employees have to do and are allowed to do in their positions. Each employee h...",""],
["./360018693811.html","Settings of Document type apps","Apps of the Document type have specific settings to make work with documents easier. You can:",""],
["./404.html","404","404 Page not found",""],
["./app-registration-settings.html","Set up registration in document apps","In BRIX you can register files uploaded as items of Document-type apps. The registered documents are displayed in the hierarchy that you have set ...",""],
["./approval-settings.html","Archiving settings for approval sheets and lists of informed users","When an app item is sent for information or approval, employees are assigned tasks and a list of informed users or approval sheet is generated on ...",""],
["./approval-sheets.html","Lists of informed users and approval sheets","Approval sheets and lists of informed users are generated each time a document is sent for review, and employees are assigned the corresponding ta...",""],
["./digital_signtature_in_apps.html","Digital signature in apps","In BRIX, an electronic digital signature (EDS) can be used to sign items of any app: a Standard app, an Event, or a Document. For instance, you ca...",""],
["./docs-versions.html","Version control and document comparison","BRIX provides the version control feature. A user can add a new version to a document created in the system, with the previous version marked...",""],
["./document_management.html","Document management","Setting up document management in BRIX comprises the following steps:",""],
["./document_template.html","Generate documents from templates","BRIX provides the generation of documents from a template for working with standard documents.",""],
["./ecm-functions.html","ECM features","BRIX ECM is a system solution within the BRIX platform for managing document workflows in a company. It includes the Document Categoriza...",""],
["./edit-documents-locally.html","Edit documents locally","In Document type apps, you can edit documents without Internet connection. The option is available in BRIX desktop application of version 2.2.1 an...",""],
["./font-settings.html","Font settings","Uploaded files may use fonts not installed in BRIX. In this case, the document text may display incorrectly when viewed or converted to .pdf.",""],
["./print-form-settings.html","Configure print form of documents","For each system app, the administrator can configure the watermark to be displayed on a document or file. Users will be able to print the document...",""],
["./print_form.html","Print form","In BRIX, files stored in app items can be printed or saved to a computer with a watermark. A ready-made or custom watermark template can be used.",""],
["./ready-made-sheets-settings.html","Templates for approval sheets and lists of informed users","The approval sheet or list of informed users created on the object page can be downloaded as an .xlsx file. A .pdf file export is also available i...",""],
["./records_classification.html","Document categorization and registration settings","Document categorization implements a hierarchy for record keeping and document registration. Registered documents are displayed in the system in a...",""],
["./records_management.html","Working with document categorization","By default, document categorization consists of the document register and the Incoming, Outgoing, and Internal document flows. They allow you to c...",""],
["./search.html","search","Platform ECM CRM Service Projects Business Solutions API SDK In this topic BRIX SDK API Platform ECM Service Projects Send feedback Ask a question...",""],
["./set-up-digital-signature.html","Set up digital signatures","The digital signature allows you to sign attributes of app items, files in Document type apps, and decisions made in approval tasks. To ...",""]];
