pageinfo = [[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null]];
pagedata = [ ["./404.html","404","404 Page not found",""],
["./archive-project.html","Archive a project","A finished project can be archived and later returned to work, if necessary. These actions are available for users with the right to edit the proj...",""],
["./change-plan-tasks.html","Edit project plan tasks","If you want to make changes to a project plan, open it in the editing mode.",""],
["./create-or-change-plan.html","Edit project plan","If you have the right to edit the plan, you can make changes to it. To do this, open the project page and in the Project Schedule widget click Edi...",""],
["./create-plan-items.html","Create project plan tasks","Types of project plan tasks The following types of tasks can be created in project plans: Task (). This is a standard task with a deadline. Such t...",""],
["./create-plan.html","Create a project plan","You can create a project plan if you are the project manager or have permissions to edit the project plan. To do this, go to the calendar plan on ...",""],
["./create-project.html","Create a project","You can add a new project in the following ways: If you are not using different project types, go to the Project register page and click +Project....",""],
["./forecast-dates.html","Set estimated dates","Estimated completion dates are a tool to monitor project progress. Compare planned and estimated dates of tasks to take timely action to meet dead...",""],
["./import-export-plan.html","Import and export a project plan","If you are working with external project management systems like MS Project, you can use the project plan import and export feature. You can ...",""],
["./plan-approval-setting.html","Configure plan approval","You can enable plan approval for any project type in the Administration &#62; Project Types workspace. Then you can publish a project plan of this ...",""],
["./plan-approval-task.html","Plan approval task","A project plan is approved by the employee specified in the approval settings. When a plan is sent for approval, this user is assigned a task that...",""],
["./plan-items-links.html","Link project plan tasks","You can define the order in which tasks are executed and set up a calendar plan. To do this, determine the dependencies between tasks. Then, if th...",""],
["./project-access-and-roles.html","Set up permissions and roles in Projects","You can easily configure access to the Projects workspace including its apps, folders, and app items. For instance, you can grant the permission t...",""],
["./project-card.html","Project page","You can view project information on its page. It consist of the Main, Project Schedule, and Files tab.",""],
["./project-files.html","Project files","You can add project documents in any way convenient for you:",""],
["./project-lifecycle.html","Project lifecycle","Work with the project is done in stages. First, you create a draft of the project and make a calendar plan with tasks. Then the project is gradual...",""],
["./project-management.html","How the Projects workspace is organized","Projects is a built-in workspace in BRIX that is used for managing the company’s projects. Here you can create neat project plans, assign tasks to...",""],
["./project-plan.html","Project plan","The project plan is shown on a project’s page on the Calendar plan tab and it consists of tasks of different types. They are placed in a certain o...",""],
["./project-resources.html","Project resources","Resources are users who are employed on projects and perform project tasks. However, they are not responsible for the tasks in which they are list...",""],
["./project-system-apps.html","Set up the Projects workspace","The settings in the Projects workspace are similar to those of any workspace. You can:",""],
["./project-task-board.html","Project task board","The list of project tasks can be shown on its page in the form of a Kanban board. The tasks will be grouped by status and will be moved from one c...",""],
["./project-tasks.html","Manage project plan tasks","Once the plan has been published, the task executor and the employee with the right to edit the plan can view it on the project page on the Projec...",""],
["./project-types.html","Project types","You can use several project types for different activities of one company. Each project type is a separate app with a unique project plan template...",""],
["./projects-functions.html","Projects features","The BRIX Projects system solution is based on the platform and extends its capabilities. It includes a workspace, apps, pages, widgets, business p...",""],
["./publish-project-plan.html","Publish a project plan","Only when a plan is published are its tasks assigned to the executors. You can publish a plan if you have the permission to edit it.",""],
["./resource-settings.html","Set up project resources","Only users included in the Administrators group can manage the settings of project resources.",""],
["./search.html","search","Platform ECM CRM Service Projects Business Solutions API SDK In this topic BRIX SDK API Platform ECM Service Projects Send feedback Ask a question...",""],
["./send-plan-for-approval.html","Send a plan for approval","If project plan approval is set up in the system, you can publish a plan only after it is approved by the responsible employee specified in the se...",""],
["./view-project-group-plans.html","View project group plans","Multiple project plans can be displayed on the app page. They will be placed under each other along the same timeline. This visualization is conve...",""],
["./working-with-resources.html","Working with resources","You can work with resources in projects if you have made the initial settings, including filling in the Resource Groups and Resources directories.",""]];
